= Projektantrag
Antonio Subašić | {docdate}
ifndef::imagesdir[:imagesdir: images]

== Wahlprogramm Plattform

=== Projektbeschreibung

Seit vielen Jahren werden Wahlen hauptsächlich in Papierform durchgeführt, was mit hohem Aufwand und möglichen Fehlern verbunden ist. Mein Ziel ist es, eine digitale Wahlprogramm-Plattform zu entwickeln, die den Wahlprozess vereinfacht, beschleunigt und gleichzeitig fehlerresistenter macht. Die Plattform soll den Schüler*innen eine unkomplizierte Möglichkeit bieten, ihre Stimme abzugeben. Neben der Stimmabgabe soll die Plattform auch weitere Funktionen, wie die Anzeige von Wahlresultaten (sowohl Klassenergebnisse als auch Gesamtergebnisse), zur Verfügung stellen.

=== Projektziele

- Entwicklung einer digitalen Plattform zur Durchführung von Wahlen
- Vereinfachung und Automatisierung des Wahlprozesses
- Beschleunigung der Stimmabgabe und Auswertung
- Minimierung von Fehlern
- Verminderung von Papierverbrauch

=== Projektnutzen

Die Nutzung der Plattform bietet eine Vielzahl von Vorteilen. In erster Linie wird der Wahlprozess deutlich effizienter und fehlerresistenter macht. Schüler*innen können ihre Stimme einfach und unkompliziert abgeben und die Wahlresultate können schnell und übersichtlich angezeigt werden. Noch dazu wird der Papierverbrauch reduziert, was einen positiven Beitrag zum Umweltschutz leistet.

=== Konsequenzen der Nichtdurführung

Ohne die Entwicklung der digitalen Wahlprogramm-Plattform bleibt der Wahlprozess weiterhin aufwendig und fehleranfällig. Die Schüler*innen müssen weiterhin ihre Stimme auf Papier abgeben und die Wahlresultate müssen manuell ausgewertet werden.